spring:
  datasource:
    name: hycan_platform
    url: jdbc:mysql://124.71.5.49:3306/hycan_platform?characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: hycanadmin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver